// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmmzorwxftfwcesqoroy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtbXpvcnd4ZnRmd2Nlc3Fvcm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODI5NjQsImV4cCI6MjA3MTM1ODk2NH0.I173NxqjYenFkmzmZosAvcrWpWZClVTTn1R22DvhtdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});